# Generated by Django 4.2 on 2023-04-28 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0003_ultimamensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropagandaUm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('imagem_empresa', models.ImageField(upload_to='imagem_empresa')),
                ('texto_empresa', models.CharField(max_length=500)),
                ('link_empresa', models.CharField(max_length=500)),
                ('ativar_propaganda', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_seguidor', models.IntegerField()),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
