# Generated by Django 4.2 on 2023-04-28 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0004_propagandaum_seguidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguidores',
            name='seguidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
