# Generated by Django 4.2 on 2023-05-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_seguidores_seguidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguidores',
            name='simounao',
            field=models.BooleanField(default=False),
        ),
    ]
